// KML emission. Returns a string. Mirrors the exact format of
// old-tools write_kml so the regression diff is byte-clean.

// Matches Python's xml.sax.saxutils.escape default: only &, <, >. Quotes
// are intentionally NOT escaped (the Python reference doesn't escape them
// either, and KML readers handle bare ' and " fine inside text content).
function xmlEscape(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export function writeKML({ layerName, rows, generatedAt }) {
  const placemarks = rows.map((r) => {
    const desc =
      `Category: ${r.category}\n` +
      `Cluster: ${r.cluster_id}\n` +
      `Wait time: ${r.wait_min_minutes}–${r.wait_max_minutes} min ` +
      `(${r.density_tier})\n` +
      `Nearby POI count: ${r.nearby_poi_count}\n` +
      `OSM: ${r.osm_type} ${r.osm_id}`;
    return (
      "      <Placemark>\n" +
      `        <name>${xmlEscape(r.name)}</name>\n` +
      `        <description>${xmlEscape(desc)}</description>\n` +
      `        <Point><coordinates>${r.longitude},${r.latitude},0</coordinates></Point>\n` +
      "      </Placemark>"
    );
  });
  const body = placemarks.join("\n");
  return (
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<kml xmlns="http://www.opengis.net/kml/2.2">\n' +
    "  <Document>\n" +
    `    <name>${xmlEscape(layerName)}</name>\n` +
    `    <description>Generated by rural-jet-lag vehicle-stations at ` +
    `${generatedAt}. ${rows.length} stations.</description>\n` +
    "    <Folder>\n" +
    `      <name>${xmlEscape(layerName)}</name>\n` +
    `${body}\n` +
    "    </Folder>\n" +
    "  </Document>\n" +
    "</kml>\n"
  );
}
